### ISSUE TITLE
[NON-ISSUE] Piccola cosa...

### ISSUE THREAD

**Issue by letruxux** [yeacark/carkbot#2]
Il bot è carino e devo dire che onestamente la mia funzione preferita à molise, ma una cosa che consiglio è togliere il messaggio "comando non valido" (ora non ricordo com'era di preciso) perché va in conflitto con altri bot. Potrei farlo da solo ma sono troppo pigro quindi baii

**Comment by yeacark** [comment]
k procederò successivamente
